### ISSUE TITLE
User: part of the form was confusing

### ISSUE THREAD

**Issue by gbls-issues** [nonprofittechy/docassemble-HousingCodeChecklist#191] opened 2022-09-15 16:58 UTC
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `download_conditions_checklist_docs`
What was confusing | There were no instructions on how to file and deliver the documents to inspectional services
Other information | 
Variable being sought | `download_conditions_checklist_docs`
Package version | `1.12.1`

**Comment by nonprofittechy** [comment] 2022-09-23 23:50
Duplicate of #94

**Closed by nonprofittechy** 2022-09-23 23:50 UTC
